/**
 * APP - BOOKS
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Book } from './book';


export interface ApiDataResponseBook { 
    status?: string;
    httpStatus?: number;
    date?: string;
    time?: string;
    zone?: string;
    data?: Book;
}

