/**
 * APP - BOOKS
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface BookSearchDTO { 
    author?: string;
    country?: string;
    language?: string;
    link?: string;
    pages?: number;
    title?: string;
    year?: number;
}

