/**
 * APP - BOOKS
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface Content { 
    id?: number;
    createdDate?: string;
    lastModifiedDate?: string;
    version?: number;
    /**
     * Extention of the file
     */
    ext?: string;
    /**
     * Extention type of the file
     */
    extension?: Content.ExtensionEnum;
    /**
     * Original name of the file
     */
    originalFileName?: string;
    /**
     * Path where the file is stored
     */
    path?: string;
    /**
     * Size of the file
     */
    fileSize?: number;
    /**
     * Type of the file
     */
    fileType?: Content.FileTypeEnum;
}
export namespace Content {
    export type ExtensionEnum = 'DOC' | 'DOCX' | 'DOT' | 'DOTX' | 'DOCM' | 'DOTM' | 'ODT' | 'OTT' | 'RTF' | 'TXT' | 'PDF' | 'XPS' | 'XML' | 'HTML' | 'HTM' | 'CSV' | 'XLS' | 'XLSX' | 'XLSM' | 'XLSB' | 'XLT' | 'XLTX' | 'XLTM' | 'ODS' | 'OTS' | 'PPT' | 'PPTX' | 'PPTM' | 'POT' | 'POTX' | 'POTM' | 'ODP' | 'OTP' | 'PPS' | 'PPSX' | 'PPSM' | 'ODG' | 'OTG' | 'VSD' | 'VSDX' | 'PUB' | 'PAGES' | 'KEY' | 'NUMBERS' | 'AI' | 'BMP' | 'CDR' | 'CGM' | 'DJVU' | 'EMF' | 'EPS' | 'EXIF' | 'GIF' | 'HEIC' | 'ICO' | 'JP2' | 'JPEG' | 'JPG' | 'PBM' | 'PCX' | 'PGM' | 'PNG' | 'PNM' | 'PPM' | 'PSD' | 'RAS' | 'RAW' | 'SVG' | 'TIF' | 'TIFF' | 'WBMP' | 'WEBP' | 'WMF' | 'XCF' | 'XPM' | 'AAC' | 'AAX' | 'ACT' | 'AIFF' | 'AMR' | 'APE' | 'AU' | 'AWB' | 'DCT' | 'DSS' | 'DVF' | 'FLAC' | 'GSM' | 'IKLAX' | 'IVS' | 'M4A' | 'M4B' | 'MMF' | 'MP3' | 'MPC' | 'MSV' | 'NMF' | 'OGG' | 'OGA' | 'OPUS' | 'RA' | 'SLN' | 'TTA' | 'VOC' | 'VOX' | 'WAV' | 'WMA' | 'WV' | '3G2' | '3GP' | 'AMV' | 'ASF' | 'AVI' | 'DRC' | 'FLV' | 'GIFV' | 'H264' | 'M4P' | 'M4V' | 'MKV' | 'MNG' | 'MOV' | 'MP2' | 'MP4' | 'MPE' | 'MPEG' | 'MPG' | 'MPV' | 'MXF' | 'NSV' | 'OGV' | 'QT' | 'RM' | 'RMVB' | 'ROQ' | 'SRT' | 'SVI' | 'VOB' | 'WEBM' | 'WMV' | 'YUV' | 'ZIP' | 'RAR' | 'TAR' | 'GZ' | '7Z' | 'EXE' | 'APP' | 'MSI' | 'APK' | 'DEB' | 'NAN';
    export const ExtensionEnum = {
        Doc: 'DOC' as ExtensionEnum,
        Docx: 'DOCX' as ExtensionEnum,
        Dot: 'DOT' as ExtensionEnum,
        Dotx: 'DOTX' as ExtensionEnum,
        Docm: 'DOCM' as ExtensionEnum,
        Dotm: 'DOTM' as ExtensionEnum,
        Odt: 'ODT' as ExtensionEnum,
        Ott: 'OTT' as ExtensionEnum,
        Rtf: 'RTF' as ExtensionEnum,
        Txt: 'TXT' as ExtensionEnum,
        Pdf: 'PDF' as ExtensionEnum,
        Xps: 'XPS' as ExtensionEnum,
        Xml: 'XML' as ExtensionEnum,
        Html: 'HTML' as ExtensionEnum,
        Htm: 'HTM' as ExtensionEnum,
        Csv: 'CSV' as ExtensionEnum,
        Xls: 'XLS' as ExtensionEnum,
        Xlsx: 'XLSX' as ExtensionEnum,
        Xlsm: 'XLSM' as ExtensionEnum,
        Xlsb: 'XLSB' as ExtensionEnum,
        Xlt: 'XLT' as ExtensionEnum,
        Xltx: 'XLTX' as ExtensionEnum,
        Xltm: 'XLTM' as ExtensionEnum,
        Ods: 'ODS' as ExtensionEnum,
        Ots: 'OTS' as ExtensionEnum,
        Ppt: 'PPT' as ExtensionEnum,
        Pptx: 'PPTX' as ExtensionEnum,
        Pptm: 'PPTM' as ExtensionEnum,
        Pot: 'POT' as ExtensionEnum,
        Potx: 'POTX' as ExtensionEnum,
        Potm: 'POTM' as ExtensionEnum,
        Odp: 'ODP' as ExtensionEnum,
        Otp: 'OTP' as ExtensionEnum,
        Pps: 'PPS' as ExtensionEnum,
        Ppsx: 'PPSX' as ExtensionEnum,
        Ppsm: 'PPSM' as ExtensionEnum,
        Odg: 'ODG' as ExtensionEnum,
        Otg: 'OTG' as ExtensionEnum,
        Vsd: 'VSD' as ExtensionEnum,
        Vsdx: 'VSDX' as ExtensionEnum,
        Pub: 'PUB' as ExtensionEnum,
        Pages: 'PAGES' as ExtensionEnum,
        Key: 'KEY' as ExtensionEnum,
        Numbers: 'NUMBERS' as ExtensionEnum,
        Ai: 'AI' as ExtensionEnum,
        Bmp: 'BMP' as ExtensionEnum,
        Cdr: 'CDR' as ExtensionEnum,
        Cgm: 'CGM' as ExtensionEnum,
        Djvu: 'DJVU' as ExtensionEnum,
        Emf: 'EMF' as ExtensionEnum,
        Eps: 'EPS' as ExtensionEnum,
        Exif: 'EXIF' as ExtensionEnum,
        Gif: 'GIF' as ExtensionEnum,
        Heic: 'HEIC' as ExtensionEnum,
        Ico: 'ICO' as ExtensionEnum,
        Jp2: 'JP2' as ExtensionEnum,
        Jpeg: 'JPEG' as ExtensionEnum,
        Jpg: 'JPG' as ExtensionEnum,
        Pbm: 'PBM' as ExtensionEnum,
        Pcx: 'PCX' as ExtensionEnum,
        Pgm: 'PGM' as ExtensionEnum,
        Png: 'PNG' as ExtensionEnum,
        Pnm: 'PNM' as ExtensionEnum,
        Ppm: 'PPM' as ExtensionEnum,
        Psd: 'PSD' as ExtensionEnum,
        Ras: 'RAS' as ExtensionEnum,
        Raw: 'RAW' as ExtensionEnum,
        Svg: 'SVG' as ExtensionEnum,
        Tif: 'TIF' as ExtensionEnum,
        Tiff: 'TIFF' as ExtensionEnum,
        Wbmp: 'WBMP' as ExtensionEnum,
        Webp: 'WEBP' as ExtensionEnum,
        Wmf: 'WMF' as ExtensionEnum,
        Xcf: 'XCF' as ExtensionEnum,
        Xpm: 'XPM' as ExtensionEnum,
        Aac: 'AAC' as ExtensionEnum,
        Aax: 'AAX' as ExtensionEnum,
        Act: 'ACT' as ExtensionEnum,
        Aiff: 'AIFF' as ExtensionEnum,
        Amr: 'AMR' as ExtensionEnum,
        Ape: 'APE' as ExtensionEnum,
        Au: 'AU' as ExtensionEnum,
        Awb: 'AWB' as ExtensionEnum,
        Dct: 'DCT' as ExtensionEnum,
        Dss: 'DSS' as ExtensionEnum,
        Dvf: 'DVF' as ExtensionEnum,
        Flac: 'FLAC' as ExtensionEnum,
        Gsm: 'GSM' as ExtensionEnum,
        Iklax: 'IKLAX' as ExtensionEnum,
        Ivs: 'IVS' as ExtensionEnum,
        M4A: 'M4A' as ExtensionEnum,
        M4B: 'M4B' as ExtensionEnum,
        Mmf: 'MMF' as ExtensionEnum,
        Mp3: 'MP3' as ExtensionEnum,
        Mpc: 'MPC' as ExtensionEnum,
        Msv: 'MSV' as ExtensionEnum,
        Nmf: 'NMF' as ExtensionEnum,
        Ogg: 'OGG' as ExtensionEnum,
        Oga: 'OGA' as ExtensionEnum,
        Opus: 'OPUS' as ExtensionEnum,
        Ra: 'RA' as ExtensionEnum,
        Sln: 'SLN' as ExtensionEnum,
        Tta: 'TTA' as ExtensionEnum,
        Voc: 'VOC' as ExtensionEnum,
        Vox: 'VOX' as ExtensionEnum,
        Wav: 'WAV' as ExtensionEnum,
        Wma: 'WMA' as ExtensionEnum,
        Wv: 'WV' as ExtensionEnum,
        _3G2: '3G2' as ExtensionEnum,
        _3Gp: '3GP' as ExtensionEnum,
        Amv: 'AMV' as ExtensionEnum,
        Asf: 'ASF' as ExtensionEnum,
        Avi: 'AVI' as ExtensionEnum,
        Drc: 'DRC' as ExtensionEnum,
        Flv: 'FLV' as ExtensionEnum,
        Gifv: 'GIFV' as ExtensionEnum,
        H264: 'H264' as ExtensionEnum,
        M4P: 'M4P' as ExtensionEnum,
        M4V: 'M4V' as ExtensionEnum,
        Mkv: 'MKV' as ExtensionEnum,
        Mng: 'MNG' as ExtensionEnum,
        Mov: 'MOV' as ExtensionEnum,
        Mp2: 'MP2' as ExtensionEnum,
        Mp4: 'MP4' as ExtensionEnum,
        Mpe: 'MPE' as ExtensionEnum,
        Mpeg: 'MPEG' as ExtensionEnum,
        Mpg: 'MPG' as ExtensionEnum,
        Mpv: 'MPV' as ExtensionEnum,
        Mxf: 'MXF' as ExtensionEnum,
        Nsv: 'NSV' as ExtensionEnum,
        Ogv: 'OGV' as ExtensionEnum,
        Qt: 'QT' as ExtensionEnum,
        Rm: 'RM' as ExtensionEnum,
        Rmvb: 'RMVB' as ExtensionEnum,
        Roq: 'ROQ' as ExtensionEnum,
        Srt: 'SRT' as ExtensionEnum,
        Svi: 'SVI' as ExtensionEnum,
        Vob: 'VOB' as ExtensionEnum,
        Webm: 'WEBM' as ExtensionEnum,
        Wmv: 'WMV' as ExtensionEnum,
        Yuv: 'YUV' as ExtensionEnum,
        Zip: 'ZIP' as ExtensionEnum,
        Rar: 'RAR' as ExtensionEnum,
        Tar: 'TAR' as ExtensionEnum,
        Gz: 'GZ' as ExtensionEnum,
        _7Z: '7Z' as ExtensionEnum,
        Exe: 'EXE' as ExtensionEnum,
        App: 'APP' as ExtensionEnum,
        Msi: 'MSI' as ExtensionEnum,
        Apk: 'APK' as ExtensionEnum,
        Deb: 'DEB' as ExtensionEnum,
        Nan: 'NAN' as ExtensionEnum
    };
    export type FileTypeEnum = 'Document' | 'Image' | 'File' | 'Executable' | 'Audio' | 'Video';
    export const FileTypeEnum = {
        Document: 'Document' as FileTypeEnum,
        Image: 'Image' as FileTypeEnum,
        File: 'File' as FileTypeEnum,
        Executable: 'Executable' as FileTypeEnum,
        Audio: 'Audio' as FileTypeEnum,
        Video: 'Video' as FileTypeEnum
    };
}


